title: Code Buddy Documentation
description: Documentation, tutorials, and how-tos for Code Buddy for Unity - project-aware GPT code generation asset
theme: just-the-docs

url: https://driftingmoose.com

aux_links:
  Asset Store: https://assetstore.unity.com/packages/slug/300457 
